using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LandscapeInstitute.Dynamics.IEntityGenerator.Classes
{
    class EntityWriter
    {

        private string LogicalName;
        private string OutputDirectory;
        private string NameSpace;
        private string OutputFile;

        public EntityWriter(string logicalName, string outputDirectory, string classNamespace)
        {
            LogicalName = logicalName;
            NameSpace = classNamespace;
            OutputDirectory = outputDirectory;
            OutputFile = Path.Combine(OutputDirectory, $"{LogicalName}.cs");

        }

        public void WriteToEntityFile(string content)
        {
            
            File.AppendAllText(OutputFile, string.Format("{0}{1}", content, Environment.NewLine));
        }

        private string Content()
        {
            return File.ReadAllText(OutputFile);
        }

        private void WriteHead()
        {

            WriteToEntityFile(@"
            //------------------------------------------------------------------------------
            // <auto-generated>
            //     This code was generated by entity generation.
            //
            //     Changes to this file may cause incorrect behavior and will be lost if
            //     the code is regenerated.
            // </auto-generated>
            //------------------------------------------------------------------------------

            using Felinesoft.Framework.Core;
            using Felinesoft.Framework.CoreInterfaces;
            using Felinesoft.Framework.Ecommerce.Models;
            using System;

            namespace " + NameSpace + @"

                class " + LogicalName  + @" 
                {

            ");
        }

        public void WriteClass(string logicalName, string dataType, Boolean Optional = false) {

            WriteToEntityFile(@"
   " + (Optional ? "[Optional]" : "") + @"
                    [FieldName(""" + logicalName + @""")]
                    public " + dataType + @" " + logicalName + @":IEntity { get; set; }");

        }

        public void WriteFoot()
        {
            WriteToEntityFile(@"
                }
            }
            ");

        }

    }

}