using Microsoft.Xrm.Sdk.Metadata;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LandscapeInstitute.Dynamics.IEntityGenerator.Classes
{
    class OptionsetWriter
    {

        public string EntityLogicalName;
        public string OptionsetName;
        public string OutputDirectory;
        public string NameSpace;
        public string OutputFile;

        private string Options;
        private string Body;

        public OptionsetWriter(string entityLogicalName, string optionsetName, string outputDirectory, string classNamespace)
        {
            EntityLogicalName = entityLogicalName;
            OptionsetName = optionsetName;
            NameSpace = classNamespace;
            OutputDirectory = Path.Combine(outputDirectory, "Optionsets");
            OutputFile = Path.Combine(OutputDirectory, $"{optionsetName}.cs");

            Directory.CreateDirectory(OutputDirectory);

            WriteBody();

        }

        public void WriteToFile(string content)
        {
            File.AppendAllText(OutputFile, string.Format("{0}{1}", content, Environment.NewLine));
        }

        private string Content()
        {
            return File.ReadAllText(OutputFile);
        }

        private void WriteBody()
        {

            Body = Body + @"
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by entity generation.
                //
                //     Changes to this file may cause incorrect behavior and will be lost if
                //     the code is regenerated.
                // </auto-generated>
                //------------------------------------------------------------------------------

                using Felinesoft.Framework.Core;
                using Felinesoft.Framework.CoreInterfaces;
                using Felinesoft.Framework.Ecommerce.Models;
                using System;

                namespace " + NameSpace + @"

                    enum " + EntityLogicalName + "_" + OptionsetName + @" 
                    {
                        {0}
                    }

                }
                ";
        }

        public void AddOption(int key, string value) {

            Options = Options + $"{key.ToString()} = " + @"""" + value + @"""" + "," + Environment.NewLine;
        }

        public void Generate()
        {

            Body = Body.Replace("{0}", Options);
            Body = Body.Replace("            ", "");
            WriteToFile(Body);

            }

        }

    }

}